### ISSUE TITLE
Nom d'utilisateur avec accents

### ISSUE THREAD

**Issue by plafrance** [KenJoelTL/DefiLecture#109]
Dans la page de demandes d'adhésions, le nom du joueur «Bob l'éponge» s'affiche avec le ? (problème avec l'encodage utf8)

**Comment by KenJoelTL** [comment]
Apparemment, la Bd utilisé sur la version en ligne du site n'est pas en UTF-8. Au niveau du code, il n'y a pas de problème. J'ai ajouté des scripts pour rebartir ou remplacer en UTF-8 la classe compte ou bien tout simplement la table contenant les comptes.
